### PR TITLE
Update to version 3.3.0a67

### PR DESCRIPTION
**Pull request by dschreij**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Update to alpha67

### CODE REVIEW

**Comment by dschreij** [comment]
@conda-forge-admin, please restart CI

**Comment by dschreij** [comment]
@conda-forge-admin, please restart CI

**Comment by dschreij** [comment]
@conda-forge-admin , please restart CI

**Comment by dschreij** [comment]
@conda-forge/core. The build keeps failing for Python 3.6 on Windows only due to dependency conflicts/incompatibilities which I don't understand. Officially this package doesn't support python 3.6 anyway (only 2.7 and 3.7 onwards), so are you ok with if I omit the failing build?

Failing build log: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=131650&view=logs&j=533b006e-c27f-58a3-8df4-b5a79e785988&t=4cbdbcdd-0d3a-5f33-da1a-97ca600eeabf

**Comment by dschreij** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
You can add this to the build section and then rerender

```
build:
  ...
  skip: True  # [not (py>36 or py2k)]
```

This should skip python 3.6.

**Comment by dschreij** [comment]
Closed in favor of https://github.com/conda-forge/opensesame-feedstock/pull/2

**Pull request closed without merging**
